apiVersion: v1
kind: Service
metadata:
  name: devops-assignment-service
spec:
  type: ClusterIP
  selector:
    app: devops-assignment
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8000
      targetPort: 8000
      protocol: TCP
     